### ISSUE TITLE
This "Hello World!" fails with your interpreter

### ISSUE THREAD

**Issue by rdebath** [SeseMueller/Brainfuck#1]
Your compiler successfully runs this; your interpreter does not.

``` bf
+[>[<-[]>+[>+++>[+++++++++++>][>]-[<]>-]]++++++++++<]>
>>>>>----.<<+++.<-..+++.<-.>>>.<<.+++.------.>-.<<+.<.
```

**Comment by SeseMueller** [comment]
Thank you, you are correct. I did not account for nested loops in the interpreter. I hope I can push a fix soon,

**Comment by SeseMueller** [comment]
I found a fix; the interpreter now passes the mandelbrot test, too. Thanks again for bringing my attention to this issue, a version with the fix should be pushed within the next 15 minutes.
